---
- name: Установка Kubernetes кластера
  hosts: k8s-cluster
  become: yes

  tasks:
    # Установка containerd
    - name: Установка зависимостей для containerd
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Создание директории для keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Добавление Docker GPG ключа (для containerd.io)
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Добавление Docker репозитория (для containerd.io)
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      register: docker_repo_result
      retries: 3
      delay: 5
      until: docker_repo_result is succeeded

    - name: Установка containerd
      apt:
        name:
          - containerd.io
        state: present
        update_cache: yes
      register: containerd_install_result
      retries: 3
      delay: 5
      until: containerd_install_result is succeeded
      notify: restart containerd

    - name: Обеспечение директории конфигурации containerd
      file:
        path: /etc/containerd
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Проверка наличия конфигурации containerd
      stat:
        path: /etc/containerd/config.toml
      register: containerd_config_stat

    - name: Генерация конфигурации containerd по умолчанию
      command: containerd config default
      register: containerd_default_config
      changed_when: false
      when: not containerd_config_stat.stat.exists

    - name: Запись конфигурации containerd по умолчанию
      copy:
        content: "{{ containerd_default_config.stdout }}"
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'
      when: not containerd_config_stat.stat.exists
      notify: restart containerd

    - name: Включение SystemdCgroup в containerd
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(\s*SystemdCgroup\s*=\s*)false'
        line: '\1true'
        backrefs: yes
      notify: restart containerd

    - name: Добавление SystemdCgroup в containerd (если отсутствует)
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*SystemdCgroup\s*='
        insertafter: '^\s*\[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options\]'
        line: '            SystemdCgroup = true'
      when: containerd_config_stat.stat.exists
      notify: restart containerd

    - name: Настройка crictl для containerd
      copy:
        dest: /etc/crictl.yaml
        content: |
          runtime-endpoint: unix:///run/containerd/containerd.sock
          image-endpoint: unix:///run/containerd/containerd.sock
          timeout: 10
          debug: false
        owner: root
        group: root
        mode: '0644'

    - name: Настройка kubelet на containerd endpoint
      copy:
        dest: /etc/default/kubelet
        content: |
          KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --node-ip={{ ansible_host }}
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart kubelet

    - name: Запуск и включение containerd
      systemd:
        name: containerd
        enabled: yes
        state: started
        daemon_reload: yes
      register: containerd_service_result
      retries: 3
      delay: 2
      until: containerd_service_result is succeeded

    # Установка Kubernetes компонентов
    - name: Установка зависимостей для Kubernetes
      apt:
        name:
          - curl
          - apt-transport-https
        state: present

    - name: Создание директории для keyrings Kubernetes
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Добавление Kubernetes GPG ключа (pkgs.k8s.io)
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'
      register: k8s_key_result
      retries: 3
      delay: 5
      until: k8s_key_result is succeeded

    - name: Добавление Kubernetes репозитория
      apt_repository:
        repo: "{{ kubernetes_repo }}"
        state: present
      register: k8s_repo_result
      retries: 3
      delay: 5
      until: k8s_repo_result is succeeded

    - name: Установка kubeadm, kubelet и kubectl
      apt:
        name:
          - "kubelet={{ kubernetes_version }}-*"
          - "kubeadm={{ kubernetes_version }}-*"
          - "kubectl={{ kubernetes_version }}-*"
        state: present
        update_cache: yes
      register: k8s_install_result
      retries: 3
      delay: 5
      until: k8s_install_result is succeeded
      notify: restart kubelet

    - name: Установка hold на пакеты Kubernetes
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Включение и запуск kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started
        daemon_reload: yes
      register: kubelet_service_result
      retries: 3
      delay: 2
      until: kubelet_service_result is succeeded

  handlers:
    - name: restart containerd
      systemd:
        name: containerd
        state: restarted

    - name: restart kubelet
      systemd:
        name: kubelet
        state: restarted
